---
bootstrap:
  server: 192.168.100.9
  username: root
  password: root

vsphere:
  server: 10.202.233.1
  username: administrator@vsphere.local
  password: <encoded:QWRtaW4hMjM=>
  tls_thumbprint: F2:23:10:0F:A0:5E:22:D0:ED:0B:88:DC:3B:CA:E0:CE:29:AA:41:F8

tkg:
  mgmt:
    cluster:
      name: arcas-mgmt
      plan: dev
    deployment:
      datacenter: /VMW-wAnywhere-DC
      datastore: /VMW-wAnywhere-DC/datastore/local-ssd-a1908
      folder: /VMW-wAnywhere-DC/vm/Arcas-Lab/Arcas-Pipeline/Management
      network: arcas-management-pg
      need_portgroup_validation: 'true'
      resource_pool: /VMW-wAnywhere-DC/host/cVMW-wAnywhere-Collab-CLU/Resources
    ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDm1J9oOPcNrIQIp6r7o6rZ28NUFxvQ4MfbVQgMZq+NJVGSfL6gPj+a2IN8UjUVKXYznthbewt49Uo+gHkiXlJDxcymHvt5IEkksVBRyvMGA18ccJdf+A2qyCOusk8a62YbipI8kJlj8ZaJeXv8OC5xT6cf8pR4sxCbw4eyhRpV87za4qRxUUO20uBPQ2HfN3HqFCZsf70yVGUl0X6NQuD4tbm1UX9s+oSNyUPj3ZocZuJFLVfk5GdVr8Ew+Pvcr/C1OEmgBC5PJ1C/xAa3W8UJqmFmeFx2wOLb33JEbdLOm8ZwljoDEKFQBP9jr+XKnRBY2ew1tHi89i0nk3Reh+lcl2V9Rn5N/fcwClm298B85mmt2V7X3pk5Pc7l7JnjG5iIilv8Nv3a2SpHgx8x0Nr5NNH+qPh2UYeICDUTsjBbhHx92Xqgj60BLIdJvEkW3wUwMOjnO0B+HthFH6Y6mTETSTUfLiO1YKj1MB0kMbZOnK9SUqUVFqHf1enrb0shqzEXMCf4ZjzjK80FEkZTaxhUNdlfWjU0PaMXRtEcnhcxxEdC72qTHAteJjw8NLFvAlUp3sgqpE/KWDu/HX9vuJgeeuUdL8uiEXFvFIxqMHiHOCVDT+4V68Pg7dazA9Zx07IYjHxzqlfbKwa3t90E1bYFzFj1VZJdZK+czLB84U10Aw== akangale@vmware.com
    control_plane:
      endpoint: "192.168.101.20"
      disk_gib: '20'
      mem_mib: '4096'
      cpus: '2'
    worker:
      endpoint: ''
      disk_gib: '20'
      mem_mib: '4096'
      cpus: '2'
  shared_services:
    cluster:
      name: arcas-shares-services
      plan: dev
    deployment:
      datacenter: /VMW-wAnywhere-DC
      datastore: /VMW-wAnywhere-DC/datastore/local-ssd-a1908
      folder: /VMW-wAnywhere-DC/vm/Arcas-Lab/Arcas-Pipeline/Shared-Service
      network: arcas-sharedService-pg
      need_portgroup_validation: 'false'
      resource_pool: /VMW-wAnywhere-DC/host/cVMW-wAnywhere-Collab-CLU/Resources
    ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDm1J9oOPcNrIQIp6r7o6rZ28NUFxvQ4MfbVQgMZq+NJVGSfL6gPj+a2IN8UjUVKXYznthbewt49Uo+gHkiXlJDxcymHvt5IEkksVBRyvMGA18ccJdf+A2qyCOusk8a62YbipI8kJlj8ZaJeXv8OC5xT6cf8pR4sxCbw4eyhRpV87za4qRxUUO20uBPQ2HfN3HqFCZsf70yVGUl0X6NQuD4tbm1UX9s+oSNyUPj3ZocZuJFLVfk5GdVr8Ew+Pvcr/C1OEmgBC5PJ1C/xAa3W8UJqmFmeFx2wOLb33JEbdLOm8ZwljoDEKFQBP9jr+XKnRBY2ew1tHi89i0nk3Reh+lcl2V9Rn5N/fcwClm298B85mmt2V7X3pk5Pc7l7JnjG5iIilv8Nv3a2SpHgx8x0Nr5NNH+qPh2UYeICDUTsjBbhHx92Xqgj60BLIdJvEkW3wUwMOjnO0B+HthFH6Y6mTETSTUfLiO1YKj1MB0kMbZOnK9SUqUVFqHf1enrb0shqzEXMCf4ZjzjK80FEkZTaxhUNdlfWjU0PaMXRtEcnhcxxEdC72qTHAteJjw8NLFvAlUp3sgqpE/KWDu/HX9vuJgeeuUdL8uiEXFvFIxqMHiHOCVDT+4V68Pg7dazA9Zx07IYjHxzqlfbKwa3t90E1bYFzFj1VZJdZK+czLB84U10Aw== akangale@vmware.com
    control_plane:
      endpoint: "192.168.102.20"
      disk_gib: '20'
      mem_mib: '4096'
      cpus: '2'
    worker:
      endpoint: ''
      disk_gib: '20'
      mem_mib: '4096'
      cpus: '2'
  workload_clusters:
    - cluster:
        name: arcas-workload
        plan: dev
      deployment:
        datacenter: /VMW-wAnywhere-DC
        datastore: /VMW-wAnywhere-DC/datastore/local-ssd-a1908
        folder: /VMW-wAnywhere-DC/vm/Arcas-Lab/Arcas-Pipeline/Workload
        network: arcas-workload-pg
        need_portgroup_validation: 'false'
        resource_pool: /VMW-wAnywhere-DC/host/cVMW-wAnywhere-Collab-CLU/Resources
      ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDm1J9oOPcNrIQIp6r7o6rZ28NUFxvQ4MfbVQgMZq+NJVGSfL6gPj+a2IN8UjUVKXYznthbewt49Uo+gHkiXlJDxcymHvt5IEkksVBRyvMGA18ccJdf+A2qyCOusk8a62YbipI8kJlj8ZaJeXv8OC5xT6cf8pR4sxCbw4eyhRpV87za4qRxUUO20uBPQ2HfN3HqFCZsf70yVGUl0X6NQuD4tbm1UX9s+oSNyUPj3ZocZuJFLVfk5GdVr8Ew+Pvcr/C1OEmgBC5PJ1C/xAa3W8UJqmFmeFx2wOLb33JEbdLOm8ZwljoDEKFQBP9jr+XKnRBY2ew1tHi89i0nk3Reh+lcl2V9Rn5N/fcwClm298B85mmt2V7X3pk5Pc7l7JnjG5iIilv8Nv3a2SpHgx8x0Nr5NNH+qPh2UYeICDUTsjBbhHx92Xqgj60BLIdJvEkW3wUwMOjnO0B+HthFH6Y6mTETSTUfLiO1YKj1MB0kMbZOnK9SUqUVFqHf1enrb0shqzEXMCf4ZjzjK80FEkZTaxhUNdlfWjU0PaMXRtEcnhcxxEdC72qTHAteJjw8NLFvAlUp3sgqpE/KWDu/HX9vuJgeeuUdL8uiEXFvFIxqMHiHOCVDT+4V68Pg7dazA9Zx07IYjHxzqlfbKwa3t90E1bYFzFj1VZJdZK+czLB84U10Aw== akangale@vmware.com
      control_plane:
        endpoint: "192.168.110.32"
        disk_gib: '20'
        mem_mib: '4096'
        cpus: '2'
      worker:
        endpoint: ''
        disk_gib: '20'
        mem_mib: '4096'
        cpus: '2'

avi:
  vm_name: "arcas-avi"
  # password: Admin!23
  password: <encoded:QWRtaW4hMjM=>
  username: admin
  # vip network
  data_network:
    name: arcas-aviMgmt-pg
    cidr: 192.168.200.0/24
    static_range: 192.168.200.5-192.168.200.45
  cloud:
    name: Default-Cloud
    se_group: 'Default-Group'
    dc: VMW-wAnywhere-DC
    pg: "arcas-aviVip-pg"
    ipam: "arcas cloud ipam"
    dns:
      name: "arcas dns profiles"
      domain: "arcas.local"
  deployment:
    datacenter: VMW-wAnywhere-DC
    folder: /VMW-wAnywhere-DC/vm/Arcas-Lab/Arcas-Pipeline/Avi-Controller
    resource_pool: /VMW-wAnywhere-DC/host/cVMW-wAnywhere-Collab-CLU/Resources
    datastore: /VMW-wAnywhere-DC/datastore/local-ssd-a1908
    network: arcas-aviMgmt-pg
    need_portgroup_validation: 'false'
    parameters:
      gateway: 192.168.200.253
      netmask: 255.255.255.0
      ip: 192.168.200.5
  conf:
    dns: [192.168.100.5]
    ntp: [139.59.55.93, 165.22.213.178]
    backup:
      passphrase: VMware123!
    cert:
      name: "New Self Signed"
      common_name: "arcas.local"
      
dhcp_validation:
  datacenter: /VMW-wAnywhere-DC
  datastore: /VMW-wAnywhere-DC/datastore/local-ssd-a1908
  folder: /VMW-wAnywhere-DC/vm/Arcas-Lab/Arcas-Pipeline/Avi-Controller
  resource_pool: /VMW-wAnywhere-DC/host/cVMW-wAnywhere-Collab-CLU/Resources
